###
GET https://backend-node-express-mongo.vercel.app/server HTTP/1.1


##################################################################### REGISTRAR USUARIO
POST  https://backend-node-express-mongo.vercel.app/auth/register HTTP/1.1
Content-Type: application/json

{
    "name":"usuario1",
    "username":"username1",
    "email":"nextTutorial2@test.com",
    "password":"123123",
    "roles":["admin"]
}

######################################################################## LOGIN
POST  https://backend-node-express-mongo.vercel.app/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"administrator@admin.com",
    "password":"123123"
}

# {
#     "email":"nextTutorial2@test.com",
#     "password":"123123"
# }

######################################################################## CONSULTAR USUARIOS
GET https://backend-node-express-mongo.vercel.app/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzIxM2E4YTI4YWNmMTVjNzU3OGU4NiIsImVtYWlsIjoiYWRtaW5pc3RyYXRvckBhZG1pbi5jb20iLCJuYW1lIjoiYWRtaW5pc3RyYXRvciIsImlhdCI6MTc0MTI2OTczNCwiZXhwIjoxNzQxMjgwNTM0fQ.7rbbG6-uDFLg2LXbFs2r7p5-VPeehFgcjJaroCtz2sk


##################################################################### CREAR USUARIO
POST  https://backend-node-express-mongo.vercel.app/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzIxM2E4YTI4YWNmMTVjNzU3OGU4NiIsImVtYWlsIjoiYWRtaW5pc3RyYXRvckBhZG1pbi5jb20iLCJuYW1lIjoiYWRtaW5pc3RyYXRvciIsImlhdCI6MTc0MTI2OTczNCwiZXhwIjoxNzQxMjgwNTM0fQ.7rbbG6-uDFLg2LXbFs2r7p5-VPeehFgcjJaroCtz2sk

{
    "username":"Empleadito2",
    "password":"123123",
    "employeeId":"1111231dss23",
    "roles":["admin"]
}

# 